### ISSUE TITLE
Create Person Input

### ISSUE THREAD

**Issue by Ocph23** [ramdhani20295/KelurahanSentani#4]
Buat Daftar Masyarakat dan Inputan , Person, Kartu Keluar dan  Detail Person

**Comment by ramdhani20295** [comment]
Gak ngerti yg ini.

**Comment by Ocph23** [comment]
Buat inputan untuk penduduk  kemudian inputan untuk Kartu keluarga dan dilanjutkan inputan untuk mendaftarkan penduduk ke dalam kartu keluarga

**Comment by ramdhani20295** [comment]
och. ok.
