### ISSUE TITLE
Create RW, RT

### ISSUE THREAD

**Issue by Ocph23** [ramdhani20295/KelurahanSentani#5]
Buat Inputan RW, RT

**Comment by Ocph23** [comment]
Bro untuk RW dan RT bisa tidak bikin viewnya, kalau kita klik rw daftar rt muncul .
jadi tambah rw dulu baru di dalamnya tambah rt

**Comment by ramdhani20295** [comment]
Gak bisa.

**Comment by Ocph23** [comment]
Harus Bisa to

**Comment by ramdhani20295** [comment]
itu pake database kh.?

**Comment by Ocph23** [comment]
saya sudah set databasenya online

**Comment by ramdhani20295** [comment]
Databasenya kok gak ada isi.?
